import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { homedir } from "node:os";

export type ExportFormat = "txt" | "docx";

export interface TranslationExportParams {
  translationText: string;
  sourceText?: string;
  title?: string;
  filenameBase?: string;
  targetLang?: string;
  formats?: ExportFormat[];
  outputDir?: string;
}

export interface ExportedTranslationFile {
  format: ExportFormat;
  path: string;
  mediaUrl: string;
  name: string;
  mimeType: string;
  sizeBytes: number;
  sha256: string;
}

function defaultExportDir(): string {
  if (process.env.PRANTE_EXPORT_DIR) return process.env.PRANTE_EXPORT_DIR;
  if (process.env.OPENCLAW_WORKSPACE_DIR) return join(process.env.OPENCLAW_WORKSPACE_DIR, "exports");
  const pranteWorkspace = join(homedir(), ".openclaw", "workspace-prante");
  if (existsSync(pranteWorkspace)) return join(pranteWorkspace, "exports");
  return join(homedir(), ".openclaw-prante", "exports");
}

function sanitizeFilenameBase(value: string | undefined): string {
  const base = (value ?? "prante_translation")
    .normalize("NFKC")
    .replace(/[\\/\0<>:"|?*]+/g, "_")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 96);
  return base || "prante_translation";
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function paragraph(text: string, style?: string): string {
  const styleXml = style ? `<w:pPr><w:pStyle w:val="${style}"/></w:pPr>` : "";
  if (!text) return `<w:p>${styleXml}</w:p>`;
  return `<w:p>${styleXml}<w:r><w:t xml:space="preserve">${xmlEscape(text)}</w:t></w:r></w:p>`;
}

function textToParagraphs(text: string): string {
  return text
    .replace(/\r\n/g, "\n")
    .split(/\n/)
    .map((line) => paragraph(line))
    .join("\n");
}

function buildDocumentXml(params: TranslationExportParams): string {
  const title = params.title?.trim() || "PRANTE Translation";
  const chunks = [
    paragraph(title, "Title"),
    paragraph(`Target language: ${params.targetLang || "unspecified"}`),
    paragraph(`Generated by PRANTE OpenClaw translator tools.`),
    paragraph(""),
    paragraph("Translation", "Heading1"),
    textToParagraphs(params.translationText),
  ];
  if (params.sourceText?.trim()) {
    chunks.push(paragraph(""), paragraph("Source", "Heading1"), textToParagraphs(params.sourceText));
  }
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
    ${chunks.join("\n    ")}
    <w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
  </w:body>
</w:document>`;
}

function buildStylesXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:sz w:val="22"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="26"/></w:rPr></w:style>
</w:styles>`;
}

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[i] = c >>> 0;
  }
  return table;
})();

function crc32(buffer: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of buffer) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function dosDateTime(date = new Date()): { time: number; date: number } {
  const year = Math.max(1980, date.getFullYear());
  const dosTime = (date.getHours() << 11) | (date.getMinutes() << 5) | Math.floor(date.getSeconds() / 2);
  const dosDate = ((year - 1980) << 9) | ((date.getMonth() + 1) << 5) | date.getDate();
  return { time: dosTime, date: dosDate };
}

function buildZip(entries: Array<{ name: string; data: Buffer }>): Buffer {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;
  const stamp = dosDateTime();
  for (const entry of entries) {
    const name = Buffer.from(entry.name, "utf8");
    const data = entry.data;
    const crc = crc32(data);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0x0800, 6); // UTF-8 file names
    local.writeUInt16LE(0, 8); // store, no compression
    local.writeUInt16LE(stamp.time, 10);
    local.writeUInt16LE(stamp.date, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28);
    locals.push(local, name, data);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(0, 10);
    central.writeUInt16LE(stamp.time, 12);
    central.writeUInt16LE(stamp.date, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(data.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt16LE(0, 30);
    central.writeUInt16LE(0, 32);
    central.writeUInt16LE(0, 34);
    central.writeUInt16LE(0, 36);
    central.writeUInt32LE(0, 38);
    central.writeUInt32LE(offset, 42);
    centrals.push(central, name);
    offset += local.length + name.length + data.length;
  }
  const centralStart = offset;
  const centralDir = Buffer.concat(centrals);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralDir.length, 12);
  end.writeUInt32LE(centralStart, 16);
  end.writeUInt16LE(0, 20);
  return Buffer.concat([...locals, centralDir, end]);
}

function buildDocx(params: TranslationExportParams): Buffer {
  const files = [
    {
      name: "[Content_Types].xml",
      data: Buffer.from(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>`, "utf8"),
    },
    {
      name: "_rels/.rels",
      data: Buffer.from(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`, "utf8"),
    },
    { name: "word/document.xml", data: Buffer.from(buildDocumentXml(params), "utf8") },
    { name: "word/styles.xml", data: Buffer.from(buildStylesXml(), "utf8") },
  ];
  return buildZip(files);
}

function uniqueFormats(formats: ExportFormat[] | undefined): ExportFormat[] {
  const requested = formats?.length ? formats : ["docx", "txt"];
  const result: ExportFormat[] = [];
  for (const item of requested) {
    if ((item === "txt" || item === "docx") && !result.includes(item)) result.push(item);
  }
  return result.length ? result : ["docx", "txt"];
}

async function writeExportFile(path: string, content: Buffer | string): Promise<ExportedTranslationFile["sha256"]> {
  await mkdir(dirname(path), { recursive: true });
  const buffer = typeof content === "string" ? Buffer.from(content, "utf8") : content;
  await writeFile(path, buffer);
  return createHash("sha256").update(buffer).digest("hex");
}

export async function exportTranslation(params: TranslationExportParams): Promise<{ ok: true; outputDir: string; files: ExportedTranslationFile[] }> {
  const translationText = params.translationText.trim();
  if (!translationText) throw new Error("translationText is required.");
  const outputDir = resolve(params.outputDir ?? defaultExportDir());
  await mkdir(outputDir, { recursive: true });
  const filenameBase = sanitizeFilenameBase(params.filenameBase ?? params.title);
  const files: ExportedTranslationFile[] = [];

  for (const format of uniqueFormats(params.formats)) {
    const name = `${filenameBase}.${format}`;
    const path = join(outputDir, name);
    const mimeType = format === "docx"
      ? "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      : "text/plain; charset=utf-8";
    const content = format === "docx"
      ? buildDocx(params)
      : `# ${params.title?.trim() || "PRANTE Translation"}\n\n${translationText}\n${params.sourceText?.trim() ? `\n\n---\n\n## Source\n\n${params.sourceText.trim()}\n` : ""}`;
    const sha256 = await writeExportFile(path, content);
    const buffer = typeof content === "string" ? Buffer.from(content, "utf8") : content;
    files.push({ format, path, mediaUrl: path, name, mimeType, sizeBytes: buffer.length, sha256 });
  }

  return { ok: true, outputDir, files };
}
